{"uid":"9f2b4b128c202467","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1663075131145,"stop":1663075131177,"duration":32},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > it.onl is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > it.onl is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Suite.eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:125:6)\n    at ./cypress/e2e/Ui/7-ver-perfil.spec.js (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:121:1)\n    at __webpack_require__ (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:20:30)\n    at 0 (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:161:18)\n    at __webpack_require__ (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:20:30)\n    at eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:84:18)\n    at eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\7-ver-perfil.spec.js:87:10)\n    at eval (<anonymous>)\nFrom previous event:\n    at runScriptsFromUrls (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:165174:136)\n    at Object.runScripts (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:165189:12)\n    at $Cypress.onSpecWindow (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:153344:75)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"c54224164ab41003","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > ito is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1662381720384,"stop":1662381720447,"duration":63}},{"uid":"8ae50d44bf8e434e","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > iton is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1662381687521,"stop":1662381687580,"duration":59}},{"uid":"8a608e7b2746307f","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > befo is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660660895269,"stop":1660660895281,"duration":12}},{"uid":"3533eaa434830f8e","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > bef is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660660894146,"stop":1660660894166,"duration":20}},{"uid":"da63917b131380ac","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > befor is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660660888769,"stop":1660660888786,"duration":17}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"9f2b4b128c202467.json","parameterValues":[]}